### Connection check
GET http://localhost:3001/

### Getting all surveys
GET http://localhost:3001/api/surveys




### Adding new survey

POST http://localhost:3001/api/surveys
Content-Type: application/json

{ "title": "Atabays Survey", "numRespond": 4,"published": 1, "user":1 }


### Delete existing survey with a given id
DELETE http://localhost:3001/api/surveys/delete/5

### Uodate numrespond

PUT http://localhost:3001/api/surveys/update/1

### updating the status of the survey
PUT http://localhost:3001/api/questions/update/published/8


### Getting all questions
GET http://localhost:3001/api/questions

### Getting all questions of the selected survey
GET http://localhost:3001/api/questions/survey/1



### Adding new questions

POST http://localhost:3001/api/questions
Content-Type: application/json

{ "question": "Describe yourself", "questiontype":0, "num":0, "min":1, "max":1, "one": "", "two": "", "three": "", "four": "", "five":"", "six":"", "seven": "", "eight": "", "nine": "", "ten" :"", "order": 1, "survey_id":2}


### Delete existing question with a given id
DELETE http://localhost:3001/api/questions/delete/2

### Moving order to down

PUT http://localhost:3001/api/questions/update/order/down/2/13



### Getting all submissions
GET http://localhost:3001/api/submissions

### Adding new submission

POST http://localhost:3001/api/submissions
Content-Type: application/json

{ "responder": "Yuri Caridi", "survey_id":1 }


### Getting number of submissions from selected survey
GET http://localhost:3001/api/submissions/number/1

### Getting number of submissions from selected survey
GET http://localhost:3001/api/submissions/number

### Getting list of submissions of selected survey
GET http://localhost:3001/api/submissions/survey/1



### Getting all answers
GET http://localhost:3001/api/answers

### Getting answers of given survey
GET http://localhost:3001/api/answers/survey/1/5

### Adding new answer

POST http://localhost:3001/api/answers
Content-Type: application/json

{ "submission_id": 13, "survey_id":1, "question_id":46, "questiontype": 1, "answer":"Memento", "one": 0, "two": 0, "three": 0, "four": 0, "five":0, "six":0, "seven": 0, "eight": 0, "nine": 0, "ten" :0}

### updating the answer

PUT http://localhost:3001/api/answers/update/two/13/44

### Uodate status of answer

PUT http://localhost:3001/api/answers/updatestatus/44/15

### updating the answer

PUT http://localhost:3001/api/answers/update/44/13
Content-Type: application/json

{ "one":0,"two":0,"three":0,"four":0,"five":0,"six":0,"seven":0,"eight":0,"nine":0,"ten":0 }

### updating the answer

PUT http://localhost:3001/api/answers/updateopen/45/13
Content-Type: application/json

{ "answer":"Hello blaaaaaaa" }