### Connection check
GET http://localhost:3001/

### Getting all surveys
GET http://localhost:3001/api/surveys


### Adding new survey

POST http://localhost:3001/api/surveys
Content-Type: application/json

{ "title": "Atabays Survey", "numRespond": 4,"published": 1, "user":1 }


### Delete existing survey with a given id
DELETE http://localhost:3001/api/surveys/delete/5




### Getting all questions
GET http://localhost:3001/api/questions


### Adding new questions

POST http://localhost:3001/api/questions
Content-Type: application/json

{ "question": "How much is your salary", "questiontype":1, "num":3, "min":1, "max":1, "one": "<1000", "two": ">1000 and <2500", "three": ">2500", "four": "", "five":"", "six":"", "seven": "", "eight": "", "nine": "", "ten" :"", "order": 2, "survey_id":1}


### Delete existing question with a given id
DELETE http://localhost:3001/api/questions/delete/2







### Getting all submissions
GET http://localhost:3001/api/submissions

### Adding new submission

POST http://localhost:3001/api/submissions
Content-Type: application/json

{ "responder": "Yuri Caridi", "survey_id":1 }


### Getting all submissions
GET http://localhost:3001/api/submissions/number/1

### Getting all submissions
GET http://localhost:3001/api/submissions/survey/1